# Generated by Django 5.2.17 on 2026-09-16 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('idioma_estrangeiro', models.CharField(blank=True, choices=[('ingles', 'Inglês'), ('espanhol', 'Espanhol')], default='', max_length=10, verbose_name='idioma estrangeiro')),
            ],
            options={
                'verbose_name': 'tentativa',
                'verbose_name_plural': 'tentativas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Linguagens', 'Linguagens, Códigos e suas Tecnologias'), ('Humanas', 'Ciências Humanas e suas Tecnologias'), ('Natureza', 'Ciências da Natureza e suas Tecnologias'), ('Matemática', 'Matemática e suas Tecnologias')], db_index=True, max_length=20, verbose_name='área')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('numero', models.PositiveIntegerField(verbose_name='número na prova')),
                ('enunciado', models.TextField(verbose_name='enunciado')),
                ('imagem', models.TextField(blank=True, default='', verbose_name='imagens')),
                ('texto_apoio', models.TextField(blank=True, default='', verbose_name='texto de apoio')),
                ('fonte', models.TextField(blank=True, default='', verbose_name='fonte')),
                ('idioma_estrangeiro', models.CharField(blank=True, choices=[('ingles', 'Inglês'), ('espanhol', 'Espanhol')], db_index=True, default='', max_length=10, verbose_name='idioma estrangeiro')),
                ('texto_apoio_1', models.TextField(blank=True, default='')),
                ('texto_apoio_2', models.TextField(blank=True, default='')),
                ('texto_apoio_3', models.TextField(blank=True, default='')),
                ('texto_apoio_4', models.TextField(blank=True, default='')),
                ('referencia_texto_1', models.TextField(blank=True, default='')),
                ('referencia_texto_2', models.TextField(blank=True, default='')),
                ('referencia_texto_3', models.TextField(blank=True, default='')),
                ('referencia_texto_4', models.TextField(blank=True, default='')),
                ('alternativa_a', models.TextField()),
                ('alternativa_b', models.TextField()),
                ('alternativa_c', models.TextField()),
                ('alternativa_d', models.TextField()),
                ('alternativa_e', models.TextField()),
                ('resposta_correta', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['area', 'ano', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('area', 'ano', 'numero', 'idioma_estrangeiro'), name='questao_unica_por_area_ano_numero_idioma')],
            },
        ),
        migrations.CreateModel(
            name='ElementoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('tipo', models.CharField(choices=[('TEXTO_APOIO', 'Texto de apoio'), ('IMAGEM', 'Imagem'), ('REFERENCIA', 'Referência'), ('ENUNCIADO', 'Enunciado')], max_length=20, verbose_name='tipo')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='simulados.questao', verbose_name='questão')),
            ],
            options={
                'verbose_name': 'elemento da questão',
                'verbose_name_plural': 'elementos da questão',
                'ordering': ['questao_id', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaTentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem na prova')),
                ('alternativa', models.CharField(blank=True, default='', max_length=1, verbose_name='alternativa marcada')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='simulados.questao', verbose_name='questão')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='simulados.tentativa', verbose_name='tentativa')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
                'ordering': ['tentativa_id', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('tentativa', 'ordem'), name='resposta_unica_por_ordem')],
            },
        ),
    ]
