# Generated by Django 5.2.17 on 2026-09-16 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProvaCompartilhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem na prova')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simulados.questao', verbose_name='questão')),
            ],
            options={
                'verbose_name': 'questão da prova da turma',
                'verbose_name_plural': 'questões da prova da turma',
                'ordering': ['prova_id', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProvaCompartilhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='código')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('idioma_estrangeiro', models.CharField(blank=True, choices=[('ingles', 'Inglês'), ('espanhol', 'Espanhol')], default='', max_length=10, verbose_name='idioma estrangeiro')),
                ('questoes', models.ManyToManyField(related_name='provas_compartilhadas', through='simulados.ItemProvaCompartilhada', to='simulados.questao', verbose_name='questões')),
            ],
            options={
                'verbose_name': 'prova da turma',
                'verbose_name_plural': 'provas de turma',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='itemprovacompartilhada',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='simulados.provacompartilhada', verbose_name='prova'),
        ),
        migrations.AddField(
            model_name='tentativa',
            name='prova_compartilhada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas', to='simulados.provacompartilhada', verbose_name='prova da turma'),
        ),
        migrations.AddConstraint(
            model_name='itemprovacompartilhada',
            constraint=models.UniqueConstraint(fields=('prova', 'ordem'), name='item_unico_por_ordem'),
        ),
    ]
