# Generated by Django 5.2.17 on 2026-09-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0002_itemprovacompartilhada_provacompartilhada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provacompartilhada',
            name='embaralhar',
            field=models.BooleanField(default=False, help_text='Cada aluno recebe as mesmas questões em uma ordem diferente.', verbose_name='embaralhar ordem por aluno'),
        ),
    ]
