# Generated by Django 5.2.17 on 2026-09-29 19:23

import simulados.models.prova_compartilhada
from django.db import migrations, models


def token_proprio_por_prova(apps, schema_editor):
    """O AddField calcula o default uma vez só: cada prova antiga ganha o seu token."""
    ProvaCompartilhada = apps.get_model("simulados", "ProvaCompartilhada")
    for prova in ProvaCompartilhada.objects.all():
        prova.token_gestor = simulados.models.prova_compartilhada.gerar_token_gestor()
        prova.save(update_fields=["token_gestor"])


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0004_questoes_ingles_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='provacompartilhada',
            name='token_gestor',
            field=models.CharField(default=simulados.models.prova_compartilhada.gerar_token_gestor, editable=False, max_length=32, verbose_name='token do gestor'),
        ),
        migrations.AddField(
            model_name='tentativa',
            name='nome_aluno',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='nome do aluno'),
        ),
        migrations.RunPython(token_proprio_por_prova, migrations.RunPython.noop),
    ]
